# Generated by Django 5.2.5 on 2025-09-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='category',
            field=models.CharField(choices=[('journals', 'Journals'), ('conference', 'Conference'), ('book_chapters', 'Book Chapters'), ('patents', 'Patents')], default='journals', max_length=20),
        ),
        migrations.AddField(
            model_name='publication',
            name='page_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_link',
            field=models.URLField(blank=True, help_text='Direct link to the publication'),
        ),
        migrations.AddField(
            model_name='publication',
            name='volume',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
