# Generated by Django 5.2.5 on 2025-09-06 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_publication_category_publication_page_no_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-publication_date', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='publication',
            name='year',
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_date',
            field=models.DateField(default=datetime.date.today, help_text='Publication date (Day/Month/Year)'),
        ),
    ]
