# Generated by Django 5.2.5 on 2025-09-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_publication_options_remove_publication_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='journal',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_date',
            field=models.DateField(help_text='Publication date (Day/Month/Year)'),
        ),
    ]
