# Generated by Django 5.2.5 on 2026-03-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_publication_journal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Short description shown in the list', max_length=500)),
                ('full_view', models.TextField(help_text='Complete view shown in the popup')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
