# Generated by Django 5.2.5 on 2026-03-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_myview'),
    ]

    operations = [
        migrations.AddField(
            model_name='myview',
            name='title',
            field=models.CharField(default='Untitled View', help_text='Title of the view', max_length=200),
        ),
    ]
